### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by zdv1g** [multifive/server#3]
[00:42:13] FATAL: Could not open the configuration file config.yml.
[00:42:38] INFO: Creating initial server instance.
[00:42:39] INFO: Pre-parsing resources: mapmanager
[00:42:41] INFO: Starting resource mapmanager (last state: Stopped).
[00:42:41] INFO: Running tasks on mapmanager: UpdatePackageFileTask.
[00:42:42] INFO: plaaaaay
[00:42:42] INFO: plaaaaay end
[00:42:42] INFO: Starting game server on port 30120
[00:42:42] INFO: Starting HTTP server on port 30120
[00:42:42] INFO: Embedded uhttpserver started.
[00:42:42] INFO: Starting resource fivem (last state: Stopped).
[00:42:42] INFO: Running tasks on fivem: UpdatePackageFileTask.
[00:42:42] INFO: Started gametype FiveM
[00:42:42] INFO: Starting resource spawnmanager (last state: Stopped).
[00:42:42] INFO: Running tasks on spawnmanager: UpdatePackageFileTask.
[00:42:42] INFO: Starting resource chat (last state: Stopped).
[00:42:42] INFO: Running tasks on chat: UpdatePackageFileTask.
[00:42:42] INFO: Starting resource fivem-map-hipster (last state: Stopped).
[00:42:42] INFO: Running tasks on fivem-map-hipster: UpdatePackageFileTask.
[00:42:42] INFO: Frame time warning: server frame took 59 msec.
[01:10:47] INFO: Creating initial server instance.
[01:10:47] INFO: Pre-parsing resources: mapmanager
[01:10:48] INFO: Starting resource mapmanager (last state: Stopped).
[00:32:01] INFO: Creating initial server instance.
[00:32:01] INFO: Creating initial server instance.
[00:32:02] INFO: Pre-parsing resources: mapmanager
[00:32:05] INFO: Creating initial server instance.
[00:32:05] INFO: Pre-parsing resources: mapmanager
[00:32:07] INFO: Starting resource mapmanager (last state: Stopped).
[00:32:08] INFO: plaaaaay
[00:32:08] INFO: plaaaaay end
[00:32:09] INFO: Starting game server on port 30120
[00:32:09] INFO: Starting HTTP server on port 30120
[00:32:09] INFO: Embedded uhttpserver started.
[00:32:09] INFO: Starting resource fivem (last state: Stopped).
[00:32:09] INFO: Started gametype FiveM
[00:32:09] INFO: Starting resource spawnmanager (last state: Stopped).
[00:32:09] INFO: Starting resource chat (last state: Stopped).
[00:32:09] INFO: Starting resource fivem-map-hipster (last state: Stopped).
[00:32:09] INFO: Frame time warning: server frame took 145 msec.
[00:42:40] INFO: Creating initial server instance.
[00:42:40] INFO: Pre-parsing resources: mapmanager
[00:42:42] INFO: Starting resource mapmanager (last state: Stopped).
[00:42:43] INFO: plaaaaay
[00:42:43] INFO: plaaaaay end
[00:42:43] INFO: Starting game server on port 30120
[00:42:43] INFO: Starting HTTP server on port 30120
[00:42:43] INFO: Embedded uhttpserver started.
[00:42:43] INFO: Starting resource fivem (last state: Stopped).
[00:42:43] INFO: Started gametype FiveM
[00:42:43] INFO: Starting resource spawnmanager (last state: Stopped).
[00:42:43] INFO: Starting resource chat (last state: Stopped).
[00:42:44] INFO: Starting resource fivem-map-hipster (last state: Stopped).
[00:42:44] INFO: Frame time warning: server frame took 35 msec.
[22:08:36] INFO: Creating initial server instance.
[22:08:36] INFO: Pre-parsing resources: mapmanager
[22:08:37] INFO: Starting resource mapmanager (last state: Stopped).
[22:08:37] INFO: Running tasks on mapmanager: UpdatePackageFileTask.
[22:08:38] INFO: plaaaaay
[22:08:38] INFO: plaaaaay end
[22:08:38] INFO: Starting game server on port 30120
[22:08:38] INFO: Starting HTTP server on port 30120
[22:08:38] INFO: Embedded uhttpserver started.
[22:08:38] INFO: Starting resource fivem (last state: Stopped).
[22:08:38] INFO: Running tasks on fivem: UpdatePackageFileTask.
[22:08:38] INFO: Started gametype FiveM
[22:08:38] INFO: Starting resource spawnmanager (last state: Stopped).
[22:08:38] INFO: Running tasks on spawnmanager: UpdatePackageFileTask.
[22:08:38] INFO: Starting resource chat (last state: Stopped).
[22:08:38] INFO: Running tasks on chat: UpdatePackageFileTask.
[22:08:38] INFO: Starting resource fivem-map-hipster (last state: Stopped).
[22:08:38] INFO: Running tasks on fivem-map-hipster: UpdatePackageFileTask.
[22:08:43] INFO: Got Client 109.195.131.117:40906
[22:08:43] INFO: 109.195.131.117:40906 : Got request /client
[22:08:43] INFO: Context: 
[22:08:43] INFO: KYRVA====>Object reference not set to an instance of an object.
[22:08:43] INFO: KYRVA====>   at uhttpsharp.HttpClientHandler.<WriteResponse>d__11.MoveNext() in ***\server-master\Vendor\uHttpSharp\uhttpsharp\HttpClient.cs:line 132
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at uhttpsharp.HttpClientHandler.<Process>d__10.MoveNext() in ***\server-master\Vendor\uHttpSharp\uhttpsharp\HttpClient.cs:line 93
[22:08:43] WARN: Error while serving : 109.195.131.117:40906
[22:08:43] INFO: Lost Client 109.195.131.117:40906

**Comment by 0x452** [comment]
did you use right httpsharp?

**Comment by zdv1g** [comment]
i download sourse from github and put to server directory:
server-master\Vendor\uHttpSharp\uhttpsharp
VS15 compiling server with no errors
client sends a package (/client) and generates an error (handshake error)

**Comment by 0x452** [comment]
try to connect to server not from lan localhost

**Comment by zdv1g** [comment]
uh i need direct connection 
How connect from console?

**Comment by zdv1g** [comment]
my config:
ListenPort: 30120

PreParseResources:
    - mapmanager

AutoStartResources:
    #- fivem-awesome1501
    - fivem
    - spawnmanager
    - chat

RconPassword: lovely

Hostname: (test)

Game: GTA5

PlatformServer: 37.46.132.72

ScriptDebug: true

DebugLog: false

# enjoy viiv
#Imports:
#    - ConfigURL: http://cache.lilycove.hacks.re/exports.json

# the following is an example for resource download offloading
#Downloads:
#    all:
#        BaseURL: http://cache.lilycove.hacks.re/
#        UploadURL: ftp://citizen:city@localhost/

DisableAuth: false

**Comment by zdv1g** [comment]
general handshake failure

**Comment by 0x452** [comment]
you connect from auth.js with localhost, right?

**Comment by zdv1g** [comment]
no i connect from server browser to my server
(internet no localhost)

**Comment by zdv1g** [comment]
YAY I FIND ERROR! httpClient.cs line 129
`            foreach (var header in response.Headers)
            {
                Logger.InfoFormat("134 NIGA" + string.Format("{0}: {1}", header.Key, header.Value));
                await writer.WriteLineAsync(string.Format("{0}: {1}", header.Key, header.Value)).ConfigureAwait(false);
            }`
 response.Headers NULL!

**Comment by 0x452** [comment]
we havent got any like this
you use not correct uhttpsharp version

**Comment by zdv1g** [comment]
Give me link to correct version PLZ
